#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "Komutu RooT Yetkisi ile çalıştırın" 
   exit 1
fi
 cat << "EOF"
'########::'##::::'##:'########:::'######:::::'###::::'##:::'##::::'###:::::::
 ##.... ##: ##:::: ##: ##.... ##:'##... ##:::'## ##:::. ##:'##::::'## ##::::::
 ##:::: ##: ##:::: ##: ##:::: ##: ##:::..:::'##:. ##:::. ####::::'##:. ##:::::
 ########:: ##:::: ##: ########::. ######::'##:::. ##:::. ##::::'##:::. ##::::
 ##.... ##: ##:::: ##: ##.. ##::::..... ##: #########:::: ##:::: #########::::
 ##:::: ##: ##:::: ##: ##::. ##::'##::: ##: ##.... ##:::: ##:::: ##.... ##::::
 ########::. #######:: ##:::. ##:. ######:: ##:::: ##:::: ##:::: ##:::: ##::::
........::::.......:::..:::::..:::......:::..:::::..:::::..:::::..:::::..:::::
:'######::'########:'##::::::::::'###::::'##::::'##:                          
'##... ##: ##.....:: ##:::::::::'## ##::: ###::'###:                          
 ##:::..:: ##::::::: ##::::::::'##:. ##:: ####'####:                          
. ######:: ######::: ##:::::::'##:::. ##: ## ### ##:                          
:..... ##: ##...:::: ##::::::: #########: ##. #: ##:                          
'##::: ##: ##::::::: ##::::::: ##.... ##: ##:.:: ##:                          
. ######:: ########: ########: ##:::: ##: ##:::: ##:                          
:......:::........::........::..:::::..::..:::::..::                          
:'#######::'##::::::::'######::'##::::'##:'##::: ##:                          
'##.... ##: ##:::::::'##... ##: ##:::: ##: ###:: ##:                          
 ##:::: ##: ##::::::: ##:::..:: ##:::: ##: ####: ##:                          
 ##:::: ##: ##:::::::. ######:: ##:::: ##: ## ## ##:                          
 ##:::: ##: ##::::::::..... ##: ##:::: ##: ##. ####:                          
 ##:::: ##: ##:::::::'##::: ##: ##:::: ##: ##:. ###:                          
. #######:: ########:. ######::. #######:: ##::. ##:                          
:.......:::........:::......::::.......:::..::::..::                                            \|___|                   \/____/                  \/____/          ~~                       \/____/       

EOF

echo -n "Lütfen Kullanıcı Oturum İsmini giriniz "
echo " "
echo -n "Örnek ortak01,cekirgedh,gemlik,idh"
echo " "
read -p 'Kullanıcı Adı: ' user

is_yap(){
    echo "$user  ALL=NOPASSWD: /bin/systemctl restart arksignerd.service" >> /etc/sudoers &&
    systemctl restart sudo
}

dizin=/home/$user/Masaüstü/ArkRes

masaustune_buton(){
    cat  << EOF  > $dizin
    #!/bin/bash
    export DISPLAY=:1
    export DISPLAY=:0
    zenity --question --title="" --text "Arksigner Restart" --ok-label="Restart" --cancel-label="Çıkış"
    if [ $? -eq 0 ]
    then
        notify-send 'Arksigner' 'Restart İşlemi Başlıyor'
    fi
    sudo systemctl restart arksignerd.service &&
    status=$(systemctl status arksignerd.service | grep Active | awk '{print $2}')
    if [[ $status == 'active' ]]
    then
        notify-send 'Arksigner' 'ÇALIŞIYOR'
    else
        notify-send 'Arksigner' 'ÇALIŞMIYOR!'
    fi
EOF
}

is_yap $user 
masaustune_buton $dizin 
chmod 777 $dizin

echo ""
echo "BİTTİ"
echo ""
